name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d63bd728ed0195ffca6db82fee6a221d8a45925ca8a2f4109d01058adb6b9b8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
