name = "OneClient 1.8.9 Forge [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.8.9-forge"
update-url = "oneclient/generated/qol-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9c7af3663c3312afb6cd525d7ab34f155a0595aaea6b9ae81a50fcf8f69509c"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
