name = "OneClient 1.8.9 Forge [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.8.9-forge"
update-url = "oneclient/generated/qol-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f6a9f432e7051e97fb293e257fa8e971cdd5866dda62f1e1cd3c72d14fa2751"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
