name = "OneClient 1.8.9 Forge [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.8.9-forge"
update-url = "oneclient/generated/qol-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2609c4a66a5f73b64f5eb98b010d695ab0a6fa6fbcec70aab3fa2d2dc28f3bd"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
