name = "OneClient 1.8.9 Forge [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.8.9-forge"
update-url = "oneclient/generated/pvp-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ffe657187740c9097eef3f047cc0a06fa3f71a90fe9e37f525bcfbdcca427c1"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
