name = "OneClient 1.8.9 Forge [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.8.9-forge"
update-url = "oneclient/generated/performance-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07067fd3a8eda12f386d89d2078b3d88e9ea1cf82dd1086b0188e31071f927dd"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
