name = "OneClient 1.21.4 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.4-fabric"
update-url = "oneclient/generated/pvp-1.21.4-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54788b6f7f7dee4a16a837df1fd0fe283da2851c39b2c622bf56159fd526c43c"

[versions]
fabric = "0.18.1"
minecraft = "1.21.4"
