name = "OneClient 1.8.9 Forge [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.8.9-forge"
update-url = "oneclient/generated/utility-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e863f6457120831c5fc6ef4992bbff6b3458521e82907f559e5d66de7a477617"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
