name = "OneClient 1.21.5 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.5-fabric"
update-url = "oneclient/generated/hud-1.21.5-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc4251fb90fa3ffad2bd87543300c08287964845b42c74f955edde2ecd6f88a5"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
