name = "OneClient 1.21.4 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.4-fabric"
update-url = "oneclient/generated/utility-1.21.4-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "500ec3e5361cc53605a002ea04a4c0753fff9552d0e797c1db3d37699037d4db"

[versions]
fabric = "0.18.1"
minecraft = "1.21.4"
