name = "OneClient 1.21.4 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.4-fabric"
update-url = "oneclient/generated/qol-1.21.4-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4df600c58fccd1234b20381246664f362b17ad57d73fd81fb227dadb5bb86bf5"

[versions]
fabric = "0.18.1"
minecraft = "1.21.4"
