name = "OneClient 1.8.9 Forge [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.8.9-forge"
update-url = "oneclient/generated/hud-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f78372e93e7ba04c96f0f749a5f948a795cddf21c58e85c82bbdbc1855c69149"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
