name = "OneClient 1.21.8 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.8-fabric"
update-url = "oneclient/generated/qol-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24faf4e1d931fca2c29d0d801db09c5b0d5187a9807f1fb44d1a0b5260cddd22"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
