name = "OneClient 1.21.8 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.8-fabric"
update-url = "oneclient/generated/qol-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7114423da8253dc91d6e75c41b4919cac7cc28874bc1552773d3ec6f94f963f7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
