name = "OneClient 1.21.5 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
category = "Utility"
id = "utility-1.21.5-fabric"
update-url = "oneclient/generated/utility-1.21.5-fabric"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b81c9e9d9e6e21a9865a2dded0dfd77e7683d679b98fe5b0114eaed9a31f17e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
