name = "OneClient 1.21.5 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.5-fabric"
update-url = "oneclient/generated/performance-1.21.5-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e69601c1bde5568bd18228ca9107f52029193f59a4abd84a31e9ef4f00ba3927"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
