name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c839562c3b078fbdc4ed21a7fb2ff53c41d27c185a970bf746993a6af3cc750"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
