name = "OneClient 1.21.8 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.8-fabric"
update-url = "oneclient/generated/performance-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b08b4b30b3dd4858a183e9db2959eff693bed2677200e11e616ed4bdf4f0463b"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
