name = "OneClient 1.21.8 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.8-fabric"
update-url = "oneclient/generated/performance-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10025bc1f2590d8a23a1ce7360ec48b8c6c2c5daf5d2bdc36d43c1ec890f22ce"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
