name = "OneClient 1.21.4 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.4-fabric"
update-url = "oneclient/generated/hud-1.21.4-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b813677b5ba84a564da7df5fbf8010d26c6c2edfec1a48e5cdd1afa794efa3c6"

[versions]
fabric = "0.18.1"
minecraft = "1.21.4"
