name = "OneClient 1.21.4 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Performance"
id = "performance-1.21.4-fabric"
update-url = "oneclient/generated/performance-1.21.4-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a267d672a536f5cac532a7423c0f3a3b11579d0e52a4bb12fa724215a34fccd"

[versions]
fabric = "0.18.1"
minecraft = "1.21.4"
