name = "OneClient 1.21.8 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.8-fabric"
update-url = "oneclient/generated/utility-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31623606298a53da9b27b6a3df793117c94980e8ec6925e181e75c175a904d27"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
